# Generated by Django 6.0.6 on 2026-06-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bok',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
